spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
#    password: psltest
#    url: jdbc:postgresql://192.168.100.44:30001/postgresdb
#    username: admin
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/market-notes

  liquibase:
    change-log: 'classpath:db/master.xml'

#  level:
#    org.hibernate:
#      SQL: debug

yahoo:
  api-url: https://query1.finance.yahoo.com

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

refresh-companies:
  cron: '0 0 17 ? * MON-FRI'

user-report:
  cron: '0 10 17 ? * MON-FRI'
