### Add note
POST http://localhost:8080/add-note
content-type: application/json

{
    "externalId": "ELT_WSE",
    "noteContent": "This is a note35345345"
}

### test remote
GET http://192.168.100.44:30080/actuator/health

### get company
GET http://localhost:8080/company/ELT_WSE