### Load companies
#POST http://localhost:8080/load-companies
POST http://192.168.100.44:30080/load-companies
content-type: application/json

{
  "companies": [
    {
      "companyName": "Alior Bank",
      "stockSymbol": "ALR",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "PLW.WA"
    },
    {
      "companyName": "Polenergia",
      "stockSymbol": "PEP",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "PEP.WA"
    },
    {
      "companyName": "Police",
      "stockSymbol": "PCE",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "PCE.WA"
    },
    {
      "companyName": "Rafako",
      "stockSymbol": "RAF",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "RAF.WA"
    },
    {
      "companyName": "Sanok Rubber Company",
      "stockSymbol": "SNK",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "SNK.WA"
    },
    {
      "companyName": "Scope Fluidics",
      "stockSymbol": "SCP",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "SCP.WA"
    },
    {
      "companyName": "Selena FM",
      "stockSymbol": "SEL",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "SEL.WA"
    },
    {
      "companyName": "Shoper",
      "stockSymbol": "SHP",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "SHO.WA"
    },
    {
      "companyName": "SpyroSoft",
      "stockSymbol": "SPR",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "SPR.WA"
    },
    {
      "companyName": "Stalexport Autostrady",
      "stockSymbol": "STX",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "STX.WA"
    },
    {
      "companyName": "Stalprodukt",
      "stockSymbol": "STP",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "STP.WA"
    },
    {
      "companyName": "Sunex",
      "stockSymbol": "SNX",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "SNX.WA"
    },
    {
      "companyName": "Sygnity",
      "stockSymbol": "SGN",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "SGN.WA"
    },
    {
      "companyName": "Synthaverse",
      "stockSymbol": "SYN",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "SVE.WA"
    },
    {
      "companyName": "Torpol",
      "stockSymbol": "TOR",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "TOR.WA"
    },
    {
      "companyName": "Toya",
      "stockSymbol": "TOA",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "TOA.WA"
    },
    {
      "companyName": "Unimot",
      "stockSymbol": "UNI",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "UNI.WA"
    },
    {
      "companyName": "VRG",
      "stockSymbol": "VRG",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "VRG.WA"
    },
    {
      "companyName": "Vercom",
      "stockSymbol": "VRC",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "VRC.WA"
    },
    {
      "companyName": "Vigo Photonics",
      "stockSymbol": "VGO",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "VGO.WA"
    },
    {
      "companyName": "Votum",
      "stockSymbol": "VOT",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "VOT.WA"
    },
    {
      "companyName": "Voxel",
      "stockSymbol": "VOX",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "VOX.WA"
    },
    {
      "companyName": "Wawel",
      "stockSymbol": "WWL",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "WWL.WA"
    },
    {
      "companyName": "Wielton",
      "stockSymbol": "WLT",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "WLT.WA"
    },
    {
      "companyName": "Wittchen",
      "stockSymbol": "WTC",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "WTN.WA"
    },
    {
      "companyName": "XTPL",
      "stockSymbol": "XTP",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "XTP.WA"
    },
    {
      "companyName": "ZE PAK",
      "stockSymbol": "ZEP",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "ZEP.WA"
    },
    {
      "companyName": "Śnieżka",
      "stockSymbol": "SKA",
      "stockMarketSymbol": "WSE",
      "dataProviderSymbol": "SKA.WA"
    }
  ]
}