### Add note
POST http://localhost:8080/add-note
content-type: application/json

{
    "externalId": "ALR_WSE",
    "noteContent": "This is a note35345345"
}

### test remote
GET http://market-notes-api.localhost/actuator/health

### get company
GET http://localhost:8080/company/ELT_WSE

### add add account
POST http://192.168.100.44:30080/user-account/register
content-type: application/json

{
  "username": "jankowalski",
  "email": "ajemromek@gmail.com"
}

### add company comment
POST http://localhost:8080/user-account/company-comment
content-type: application/json

{
  "userAccountExternalId": "c9ee6d8c-7229-481f-a106-412a8e0eabe7",
  "stockCompanyExternalId": "VOT_WSE",
  "noteContent": "good company"
}

### test
GET http://localhost:8080/stock-market/test

### refresh companies
GET http://localhost:8080/refresh-companies-scheduler/invoke

### user report
GET http://192.168.100.44:30080/actuator/prometheus

### companies summary
GET http://localhost:8080/companies-summary

### company-detail-summary
GET http://localhost:8080/company-detail-summary?stockCompanyExternalId=ELT_WSE

### add account
POST http://localhost:8080/event/add-account
content-type: application/json

{
  "userAccountExternalId": "0e26a4dd-e003-4d82-8d6f-0aeb8f208a3c",
  "email": "krzystofnowak@market-notes.pl",
  "username": "Krzysztof Nowak"
}

