spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    generateDdl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate:
      SQL: debug
    #  orm.jdbc.bind: trace
yahoo:
  api-url: https://query1.finance.yahoo.com
