spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    generateDdl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate:
      SQL: debug

yahoo:
  api-url: https://query1.finance.yahoo.com
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always