spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp-relay.brevo.com
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true

  liquibase:
    change-log: 'classpath:db/master.xml'

#  level:
#    org.hibernate:
#      SQL: debug

yahoo:
  api-url: https://query1.finance.yahoo.com
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

  health:
    mail:
      enabled: false

refresh-companies:
  cron: '0 0 17 ? * MON-FRI'

user-report:
  cron: '0 10 17 ? * MON-FRI'


